/* Generated By:JavaCC: Do not edit this line. ExpressionsConstants.java */
package com.expressionparser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 1;
  /** RegularExpression Id. */
  int MINUS = 2;
  /** RegularExpression Id. */
  int MUL = 3;
  /** RegularExpression Id. */
  int DIV = 4;
  /** RegularExpression Id. */
  int MOD = 5;
  /** RegularExpression Id. */
  int POWER = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int FLOAT = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "<INT>",
    "<FLOAT>",
    "<DIGIT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
