/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package com.expressionparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 1;
  /** RegularExpression Id. */
  int MINUS = 2;
  /** RegularExpression Id. */
  int MUL = 3;
  /** RegularExpression Id. */
  int DIV = 4;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<INT>",
    "<DIGIT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
